### ISSUE TITLE
Add CSS description to project

### ISSUE THREAD

**Issue by T-Damer** [necolo/use-scroll-shadow#1]
Something like:
# If you want to restyle the shadow
Do this in your `index.css` file:
```css
.scroll-shadow-box:before {
  background: linear-gradient(
    180deg,
    rgba(0, 0, 0, 0.5),
    transparent
  ) !important;
}
.scroll-shadow-box:after {
  background: linear-gradient(0deg, rgba(0, 0, 0, 0.5), transparent) !important;
}
```

And thanks, it works like a clock :)
